### ISSUE TITLE
Help with cloudflare worker setup

### ISSUE THREAD

**Issue by ovargasp** [dtankdempse/m3u-playlist-proxy#2]
I'm trying to put the m3u-playlist proxy to work in the dash.cloudflare.com environment, with you documentation it was very easy to set the docker and make it work, as for the cploudflare I managed to create the worker, edit the code and get it to load, but I can't get it work.

this is my local playlist url:

http://192.168.0.YYY:4123/playlist?url=https%3A%2F%2Fbit.ly%2Fddy-m3u1&data=UmVmZXJlcj1odHRwczovL2lsb3ZldG9wbGF5Lnh5ei98T3JpZ2luPWh0dHBzOi8vaWxvdmV0b3BsYXkueHl6L3xVc2VyLUFnZW50PU1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyOS4wLjAuMCBTYWZhcmkvNTM3LjM2

with this playlist I can use all channels from the playlist

this is the cloudflare worker url:
https://*************.workers.dev/playlist?url=https%3A%2F%2Fbit.ly%2Fddy-m3u1&data=UmVmZXJlcj1odHRwczovL2lsb3ZldG9wbGF5Lnh5ei98T3JpZ2luPWh0dHBzOi8vaWxvdmV0b3BsYXkueHl6fFVzZXItQWdlbnQ9TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTI5LjAuMC4wIFNhZmFyaS81MzcuMzY

I noticed that both data payloads should look the same if the url and custom headers are equal. But the first playlist works inmediatly and the second one doesn't work at all, it just jumps from one channel to the next all the way to the end of the playlist (it loads the channels list, by the way). I even get to see the requests the player sends to the worker in the cloudflare logs tool so I know is getting to the worker but the player stays in buffering for ever.

Any help or ideas will be appreciated. :)

**Comment by dtankdempse** [comment]
The issue isn't with the data payload—it's that the Cloudflare Worker no longer works with DaddyLive. Their server returns a 403 response when it detects requests from a Worker. You’ll need to use another option. I’ll be adding alternatives like Vercel soon.

Also, I edited your post to remove the Cloudflare URL.

**Comment by ovargasp** [comment]
OK thanks I thought I was doing something wrong with the configuration. And thanks for the sanitising of the cloudflare url.
