### ISSUE TITLE
support for more than one provider/m3u merger?

### ISSUE THREAD

**Issue by aniel300** [dtankdempse/m3u-playlist-proxy#4]
can u support for more than one provider/m3u merger?

**Comment by dtankdempse** [comment]
Vercel does not allow storing files directly on the server since its serverless architecture only provides temporary storage during each function execution. As a result, the user would need to use third-party storage options like Dropbox, Google Drive, or Amazon S3 to save the merged playlists.

I know you are running the script using the Dockerfile option. However, I'm just trying to think of how I can make this work for everyone, so I will look more into how I could make this work. Thanks.

**Comment by dtankdempse** [comment]
Yeah, im thinking it can work with comma separated playlist url's. 

url1,url2,url3

So I'll add support for that in the changes im working on now.

**Comment by aniel300** [comment]
thank u

**Comment by aniel300** [comment]
any update?

**Comment by dtankdempse** [comment]
Yeah, I coded it yesterday but wanted to test it first. Then an issue with PlutoTV took me away from it today. I should have it tested and released by tomorrow.

**Comment by aniel300** [comment]
ok good, can't wait to test it out. it will be available in the docker image, right?

**Comment by dtankdempse** [comment]
Yes, it’s going out on all the options I’ve listed. The update will include the requests from here as well as from [#issue5](https://github.com/dtankdempse/m3u-playlist-proxy/issues/5).

**Comment by aniel300** [comment]
ok cool. will check and deploy tomorrow, thanks again

**Comment by aniel300** [comment]
i see some activity in the repo. is it ready?

**Comment by aniel300** [comment]
will do. can u update the compose. idk how to go about it

**Comment by aniel300** [comment]
does the url has to be added via the webui or can they be added in the compose file as an env?

**Comment by dtankdempse** [comment]
They need to be added through the form. I'm not quite sure what you're trying to achieve by setting an environment variable.

**Comment by aniel300** [comment]
it is easier for me to add the urls thought the docker compose. something like:
`-urls=url1,url2,etc`

i will try using the webui as well, thank u.

**Comment by dtankdempse** [comment]
I don't use Docker or Compose very often, so I'm just trying to understand why setting it up this way is easier or more beneficial.

**Comment by aniel300** [comment]
becuase docker compose to deply my container but is ok i can use the webui as well
